version: '3'
services:
  # PHP Service
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker-config/Dockerfile
    container_name: tiny-url-app
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    working_dir: /var/www/tiny-url
    volumes:
      - ./:/var/www/tiny-url # Including this because docker-entrypoint takes really long to install composer packages and this will cache vendor files locally
      - ./docker-config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - tiny-url-app-network

  # MySQL Service
  db:
    image: mysql:5.7.22
    container_name: tiny-url-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tiny-url
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: tiny-url-admin
      MYSQL_PASSWORD: Adm1n
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - tiny-url-app-network

  # phpMyAdmin Service (Only used for development purposes)
  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: phpmyadmin/phpmyadmin
  #   container_name: tiny-url-phpmyadmin
  #   restart: always
  #   ports:
  #     - '8080:80'
  #   environment:
  #     PMA_HOST: db
  #   networks:
  #     - tiny-url-app-network

# Docker Networks
networks:
  tiny-url-app-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local